
import { useState, useEffect } from 'react';
import axios from 'axios';
import { initObservability, attachAxiosInterceptor, getOrCreateCorrelationId } from 'observability-client-js';
import './App.css';

// Initialize SDK (Fetch instrumentation is on by default)
initObservability({
  allowList: [/localhost/, /127\.0\.0\.1/]
});

// Create Axios instance and attach interceptor
const api = axios.create();
attachAxiosInterceptor(api, {
  allowList: [/localhost/, /127\.0\.0\.1/]
});

function App() {
  const [correlationId, setCorrelationId] = useState<string>('');
  const [responseData, setResponseData] = useState<any>(null);
  const [error, setError] = useState<string>('');

  useEffect(() => {
    // Get the ID generated by the SDK on startup
    setCorrelationId(getOrCreateCorrelationId());
  }, []);

  const clearState = () => {
    setResponseData(null);
    setError('');
  };

  const callBackendFetch = async () => {
    clearState();
    try {
      // Calls /api/hello via Vite proxy -> http://localhost:8080/hello
      const response = await fetch('/api/hello');
      const data = await response.text();
      setResponseData({
        body: data,
        headers: {
          'x-correlation-id': response.headers.get('x-correlation-id')
        }
      });
      // Update local state if backend returned a new ID (optional)
      setCorrelationId(getOrCreateCorrelationId());
    } catch (err: any) {
      setError(err.message);
    }
  };

  const callBackendAxios = async () => {
    clearState();
    try {
      // Calls /api/hello via Vite proxy
      const response = await api.get('/api/hello');
      setResponseData({
        body: response.data,
        headers: {
          'x-correlation-id': response.headers['x-correlation-id']
        }
      });
      setCorrelationId(getOrCreateCorrelationId());
    } catch (err: any) {
      setError(err.message);
    }
  };

  return (
    <div className="container" style={{ padding: '2rem', fontFamily: 'sans-serif' }}>
      <h1>Observability Demo</h1>

      <div style={{ marginBottom: '2rem', padding: '1rem', background: '#f5f5f5', borderRadius: '4px' }}>
        <strong>Current Browser Correlation ID:</strong>
        <code style={{ display: 'block', marginTop: '0.5rem', fontSize: '1.2em', color: '#0969da' }}>
          {correlationId}
        </code>
      </div>

      <div style={{ display: 'flex', gap: '1rem', marginBottom: '2rem' }}>
        <button onClick={callBackendFetch} style={{ padding: '0.5rem 1rem', cursor: 'pointer' }}>
          Call /hello (Fetch)
        </button>
        <button onClick={callBackendAxios} style={{ padding: '0.5rem 1rem', cursor: 'pointer' }}>
          Call /hello (Axios)
        </button>
      </div>

      {error && (
        <div style={{ color: 'red', marginBottom: '1rem' }}>
          <strong>Error:</strong> {error}
        </div>
      )}

      {responseData && (
        <div style={{ border: '1px solid #ddd', padding: '1rem', borderRadius: '4px' }}>
          <h3>Backend Response</h3>
          <pre>{JSON.stringify(responseData.body, null, 2)}</pre>

          <h4>Response Headers</h4>
          <pre>{JSON.stringify(responseData.headers, null, 2)}</pre>

          <div style={{ marginTop: '1rem', fontSize: '0.9em', color: '#666' }}>
            Verify that the <code>x-correlation-id</code> matches the browser ID above!
          </div>
        </div>
      )}
    </div>
  );
}

export default App;
